services:
  backend:
    build: ./backend
    container_name: crypto_backend
    command: >
      sh -c "celery -A config worker -l INFO &
             celery -A config beat -l INFO &
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    extra_hosts:  # ← Добавь это для Linux
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=crypto_db
      - DB_USER=crypto_user
      - DB_PASSWORD=crypto_password
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: crypto_redis
    ports:
      - "6379:6379"

  # ❌ Убери блок postgres — он уже запущен
  # postgres:
  #   ...

  frontend:
    build: ./frontend
    container_name: crypto_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend